package com.portfolio.auth.gateway;

public enum WebSocketErrorType {
    INVALID_JSON,
    UNKNOWN_MESSAGE_TYPE,
    MISSING_REQUIRED_FIELD,
    CLIENT_NOT_FOUND,
    SERVICE_NOT_FOUND,
    FLOW_FAILED,
    RATE_LIMITED,
    ORIGIN_NOT_ALLOWED,
    SESSION_NOT_FOUND,
    SESSION_EXPIRED,
    SESSION_REVOKED,
    SESSION_CLIENT_MISMATCH,
    SESSION_SERVICE_MISMATCH,
    SESSION_REQUIRED,
    INVALID_SESSION_REQUEST
}
